apiVersion: v2
name: kueue
description: Kueue is a set of APIs and controllers for job queueing.
appVersion: "v0.14.1"
version: 0.1.0
home: https://github.com/giantswarm/kueue-app
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
sources:
  - https://github.com/kubernetes-sigs/kueue
annotations:
  application.giantswarm.io/team: planeteers
